In [7]:
import numpy as np
import pandas as pd


In [16]:
import pandas as pd
xl = pd.ExcelFile(r'C:\Users\ASUS ZenBook\OneDrive\Desktop\clfd.xlsx')
df = pd.read_excel(xl, 0, header=None)
print(df)

       0   1   2   3     4     5     6     7     8     9     10    11   12  \
0   Index  A1  A2  A3    A4    A5    A6    A7    A8    A9   A10   A11  A12   
1       1  36  27  71   8.1  3.34  11.4  81.5  3243   8.8  42.6  11.7   21   
2       2  35  23  72  11.1  3.14    11  78.8  4281   3.6  50.7  14.4    8   
3       3  44  29  74  10.4  3.21   9.8  81.6  4260   0.8  39.4  12.4    6   
4       4  47  45  79   6.5  3.41  11.1  77.5  3125  27.1  50.2  20.6   18   
..    ...  ..  ..  ..   ...   ...   ...   ...   ...   ...   ...   ...  ...   
56     56  28  32  81     7  3.27  12.1    81  3665   7.5  51.6  13.2    4   
57     57  45  33  76   7.7  3.39  11.3  82.2  3152  12.1  47.3  10.9   14   
58     58  45  24  70  11.8  3.25  11.1  79.8  3678     1  44.8    14    7   
59     59  42  83  76   9.7  3.22     9  76.2  9699   4.8  42.2  14.5    8   
60     60  38  28  72   8.9  3.48  10.7  79.8  3451  11.7  37.5    13   14   

     13   14   15       16  
0   A13  A14  A15        B  
1    

In [17]:
A=np.array(df)
print(A)

[['Index' 'A1' 'A2' ... 'A14' 'A15' 'B']
 [1 36 27 ... 59 59 921.87]
 [2 35 23 ... 39 57 997.875]
 ...
 [58 45 24 ... 8 56 895.696]
 [59 42 83 ... 49 54 911.817]
 [60 38 28 ... 39 58 954.442]]


In [18]:

X=(A[1:60, 1:16])
X=np.array(X, dtype='float')
print(X)

[[3.600e+01 2.700e+01 7.100e+01 8.100e+00 3.340e+00 1.140e+01 8.150e+01
  3.243e+03 8.800e+00 4.260e+01 1.170e+01 2.100e+01 1.500e+01 5.900e+01
  5.900e+01]
 [3.500e+01 2.300e+01 7.200e+01 1.110e+01 3.140e+00 1.100e+01 7.880e+01
  4.281e+03 3.600e+00 5.070e+01 1.440e+01 8.000e+00 1.000e+01 3.900e+01
  5.700e+01]
 [4.400e+01 2.900e+01 7.400e+01 1.040e+01 3.210e+00 9.800e+00 8.160e+01
  4.260e+03 8.000e-01 3.940e+01 1.240e+01 6.000e+00 6.000e+00 3.300e+01
  5.400e+01]
 [4.700e+01 4.500e+01 7.900e+01 6.500e+00 3.410e+00 1.110e+01 7.750e+01
  3.125e+03 2.710e+01 5.020e+01 2.060e+01 1.800e+01 8.000e+00 2.400e+01
  5.600e+01]
 [4.300e+01 3.500e+01 7.700e+01 7.600e+00 3.440e+00 9.600e+00 8.460e+01
  6.441e+03 2.440e+01 4.370e+01 1.430e+01 4.300e+01 3.800e+01 2.060e+02
  5.500e+01]
 [5.300e+01 4.500e+01 8.000e+01 7.700e+00 3.450e+00 1.020e+01 6.680e+01
  3.325e+03 3.850e+01 4.310e+01 2.550e+01 3.000e+01 3.200e+01 7.200e+01
  5.400e+01]
 [4.300e+01 3.000e+01 7.400e+01 1.090e+01 3.230e+00 1.210e

In [19]:
Y=(A[1:60, 16] )
Y=np.array(Y, dtype='float')
print(Y)

[ 921.87   997.875  962.354  982.291 1071.289 1030.38   934.7    899.529
 1001.902  912.347 1017.613 1024.885  970.467  985.95   958.839  860.101
  936.234  871.766  959.221  941.181  891.708  871.338  971.122  887.466
  952.529  968.665  919.729  844.053  861.833  989.265 1006.49   861.439
  929.15   857.622  961.009  923.234 1113.156  994.648 1015.023  991.29
  893.991  938.5    946.185 1025.502  874.281  953.56   839.709  911.701
  790.733  899.264  904.155  950.672  972.464  912.202  967.803  823.764
 1003.502  895.696  911.817]


In [20]:

import numpy as np
def normalize_and_add_ones(X):
    X=np.array(X)
    X_max=np.array([[np.amax(X[:, column_id])
                    for column_id in range(X.shape[1])]
                   for _ in range(X.shape[0])])
    X_min=np.array([[np.amin(X[:, column_id])
                    for column_id in range(X.shape[1])]
                   for _ in range(X.shape[0])])
    X_normalized = (X-X_min)/(X_max-X_min)
    ones=np.array([[1] for _ in range(X_normalized.shape[0])])
    return np.column_stack((ones, X_normalized))
class RidgeRegression:
    def __init__(self):
        return
    def fit(self, X_train, Y_train, LAMBDA):
        assert len(X_train.shape)==2 and \
               X_train.shape[0]==Y_train.shape[0]
        
        W=np.linalg.inv(
          X_train.transpose().dot(X_train)+LAMBDA*np.identity(X_train.shape[1])
        ).dot(X_train. transpose()).dot(Y_train)
        return W
    def predict(self, W, X_new):
        X_new=np.array(X_new)
        Y_new=X_new.dot(W)
        return Y_new
    def compute_RSS(self, Y_new, Y_predicted):
        loss=1./Y_new.shape[0]*\
             np.sum((Y_new-Y_predicted)**2)
        return loss
    def get_the_best_LAMBDA(self, X_train, Y_train):
        def cross_validation(num_folds, LAMBDA):
            row_ids=np.array(range(X_train.shape[0]))
            valid_ids=np.split(row_ids[:len(row_ids)-len(row_ids)%num_folds], num_folds)
            valid_ids[-1]=np.append(valid_ids[-1], row_ids[len(row_ids)-len(row_ids)%num_folds:])
            train_ids=[[k for k in row_ids if k not in valid_ids[i]] for i in range(num_folds)]
            aver_RSS=0
            for i in range(num_folds):
                valid_part={'X':X_train[valid_ids[i]], 'Y':Y_train[valid_ids[i]]}
                train_part={'X':X_train[train_ids[i]], 'Y':Y_train[train_ids[i]]}
                W=self.fit(train_part['X'], train_part['Y'], LAMBDA)
                Y_predicted=self.predict(W, valid_part['X'])
                aver_RSS += self.compute_RSS(valid_part['Y'], Y_predicted)
            return aver_RSS/num_folds
        def range_scan(best_LAMBDA, minimum_RSS, LAMBDA_values):
            for current_LAMBDA in LAMBDA_values:
                aver_RSS = cross_validation(num_folds=5, LAMBDA=current_LAMBDA)
                if aver_RSS<minimum_RSS:
                    best_LAMBDA = current_LAMBDA
                    minimum_RSS=aver_RSS
            return best_LAMBDA, minimum_RSS
        best_LAMBDA, minimum_RSS= range_scan(best_LAMBDA=0, minimum_RSS=1000**2,
                                        LAMBDA_values=range(50))
        LAMBDA_values=[k*1./1000 for k in range(
            max(0,(best_LAMBDA-1)*1000), (best_LAMBDA+1)*1000,1)]
        best_LAMBDA, minimum_RSS= range_scan(best_LAMBDA=best_LAMBDA, minimum_RSS=minimum_RSS, LAMBDA_values=LAMBDA_values)
        return best_LAMBDA 

X=normalize_and_add_ones(X)
X_train, Y_train =X[:50], Y[:50]
X_test, Y_test=X[50:],Y[50:]
ridge_regression=RidgeRegression()
best_LAMBDA=ridge_regression.get_the_best_LAMBDA(X_train, Y_train)
print ('Best LAMBDA:', best_LAMBDA)
W_learned=ridge_regression.fit(X_train=X_train, Y_train=Y_train, LAMBDA=best_LAMBDA)
Y_predicted=ridge_regression.predict(W=W_learned, X_new=X_test)
print (ridge_regression.compute_RSS(Y_new=Y_test, Y_predicted=Y_predicted))



Best LAMBDA: 0.002
1592.9379747078963
